version: '3'

services:
  firebase-functions:
    container_name: firebase-functions
    build:
      context: ./function-firestore
    ports:
      - 8080:8080 # FIRESTORE_PORT
      - 5005:5005 # FIRESTORE_WS_PORT
      - 4000:4000 # UI_PORT
      - 8085:8085 # PUBSUB_PORT
      - 5001:5001 # FUNCTIONS_PORT
      - 9099:9099 # AUTH_PORT