version: '3'

services:
  common-firebase-emulator:
    container_name: common-firebase-emulator
    build:
      context: ./common-firebase-emulator
    ports:
      - 8080:8080 # FIRESTORE_PORT
      - 5005:5005 # FIRESTORE_WS_PORT
      - 4000:4000 # UI_PORT
      - 9099:9099 # AUTH_PORT